version: '3.7'

services:
  karuru-backend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/karuru/src
    ports:
      - 3001:3001
    env_file:
      - ./.env.prod

  karuru-database:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: 'karuru'
      MYSQL_ROOT_PASSWORD: 'swhackaton1'
    ports:
      - 3308:3306
